import type { Feature } from '../types';

export const INSTAGRAM_FEATURES: readonly Feature[] = [
  {
    id: 'hideReadReceipts',
    label: 'Hide read receipts',
    description: 'Read direct messages without sending a seen marker',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideTyping',
    label: 'Hide typing indicator',
    description: 'Stop the typing bubble appearing in direct messages',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideStoryViews',
    label: 'Hide story views',
    description: 'Watch stories without appearing in the viewer list',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideLiveStreamViews',
    label: 'Hide live stream views',
    description: 'Watch Instagram Live videos anonymously without joining notifications',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'bypassLinkShim',
    label: 'Bypass Link Shim tracking',
    description: 'Open external links directly without routing through Instagram tracking redirect',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideSuggestedPosts',
    label: 'Hide suggested posts',
    description: 'Filter out algorithmic suggested posts from your feed',
    defaultEnabled: true,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'hideReels',
    label: 'Hide Reels & short videos',
    description: 'Hide Reels shelves and video carousels in your feed',
    defaultEnabled: true,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'hideOnlineStatus',
    label: 'Invisible mode (Hide online status)',
    description: 'Stay completely invisible on Instagram Direct without the active status dot',
    defaultEnabled: false,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideSponsoredPosts',
    label: 'Hide sponsored posts & ads',
    description: 'Hide ads and sponsored content in your Instagram feed',
    defaultEnabled: true,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'protectWebRtcIp',
    label: 'WebRTC IP leak shield',
    description: 'Prevent local and public IP exposure during Instagram Direct calls',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'scrambleDwellTime',
    label: 'Block cursor & dwell tracking',
    description: 'Stop Meta tracking mouse movements, hover heatmaps, and dwell seconds',
    defaultEnabled: false,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'stealthSearch',
    label: 'Stealth search (Zero-trace history)',
    description: 'Search accounts and tags without saving to search history or feed recommendations',
    defaultEnabled: false,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'piiLeakShield',
    label: 'Local PII & secret leak shield',
    description: 'Warn before pasting bank cards, citizen IDs, passwords, or API keys into chat',
    defaultEnabled: false,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'cleanShareLinks',
    label: 'Clean shared links (Anti-tracking)',
    description: 'Automatically strip igsh, igshid, and UTM tokens when copying links',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'antiFingerprint',
    label: 'Anti-fingerprinting shield',
    description: 'Spoof hardware telemetry, WebGL vendor, and canvas noise to prevent device fingerprinting',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
];
