import type { Feature } from '../types';

export const FACEBOOK_FEATURES: readonly Feature[] = [
  // --- Feed & Content ---
  {
    id: 'hideSponsoredPosts',
    label: 'Hide sponsored posts',
    description: 'Hide ads and sponsored content in your feed',
    defaultEnabled: true,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'hideSuggestedPosts',
    label: 'Hide suggested posts',
    description: 'Show only posts from friends and pages you follow',
    defaultEnabled: false,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'hideReels',
    label: 'Hide Reels & short videos',
    description: 'Hide Reels trays and short video clips in your feed',
    defaultEnabled: false,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'blockFeedAutoRefresh',
    label: 'Stop the feed reloading',
    description: 'Keep your place when you switch back to the tab',
    defaultEnabled: true,
    status: 'active',
    category: 'feed',
  },

  // --- Messages & Privacy ---
  {
    id: 'hideReadReceipts',
    label: 'Hide read receipts',
    description: 'Read messages without telling the sender you read them',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideTyping',
    label: 'Hide typing indicator',
    description: 'Stop the three dots appearing while you type',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideStoryViews',
    label: 'Hide story views',
    description: 'Watch stories without appearing in the viewer list',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideLiveStreamViews',
    label: 'Hide live stream views',
    description: 'Watch Facebook Live videos anonymously without appearing in the viewer list',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideInboxLastSeen',
    label: 'Hide when you opened your inbox',
    description: 'Stop Messenger recording the time you last looked at your chat list',
    defaultEnabled: false,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideOnlineStatus',
    label: 'Invisible mode (Hide online status)',
    description: 'Stay completely invisible on Messenger without the green active dot',
    defaultEnabled: false,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'protectWebRtcIp',
    label: 'WebRTC IP leak shield',
    description: 'Prevent local and public IP exposure during Messenger calls',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'hideVoicePlayed',
    label: 'Hide voice note played marker',
    description: 'Listen to voice messages without notifying the sender',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'scrambleDwellTime',
    label: 'Scramble dwell time tracking',
    description: 'Stop Meta measuring exact seconds spent looking at posts and videos',
    defaultEnabled: false,
    status: 'active',
    category: 'feed',
  },
  {
    id: 'bypassLinkShim',
    label: 'Bypass Link Shim tracking',
    description: 'Open external links directly without routing through Facebook tracking redirect',
    defaultEnabled: true,
    status: 'active',
    category: 'privacy',
  },
  {
    id: 'stealthSearch',
    label: 'Stealth search (Zero-trace history)',
    description: 'Search people and profiles without saving to recent searches or skewing recommendations',
    defaultEnabled: false,
    status: 'active',
    category: 'privacy',
  },
];
